# -------------------------------------------------------------------
#  DICCIONARIO: ENFERMERO (NO TCAE / AUXILIAR)
# -------------------------------------------------------------------

PATRONES_ENFERMERO = {
    # Formas básicas
    "ENFERMERO": "ENFERMERO",
    "ENFERMERA": "ENFERMERO",
    "ENFERMERO/A": "ENFERMERO",
    "ENFERMERA/O": "ENFERMERO",
    "ENFERMEROS": "ENFERMERO",
    "ENFERMERAS": "ENFERMERO",
    "ENFERMERIA": "ENFERMERO",

    # Combinadas con grado / diplomatura
    "GRADO EN ENFERMERIA": "ENFERMERO",
    "GRADO UNIVERSITARIO EN ENFERMERIA": "ENFERMERO",
    "DIPLOMADO EN ENFERMERIA": "ENFERMERO",
    "DIPLOMADO UNIVERSITARIO EN ENFERMERIA": "ENFERMERO",
    "DIPLOMADO-GRADO EN ENFERMERIA": "ENFERMERO",

    # Abreviaturas históricas equivalentes a enfermero/a
    "ATS": "ENFERMERO",   # ATS pertenece a ENFERMERÍA, no a TCAE
    "ATS/DUE": "ENFERMERO",
    "ATS DUE": "ENFERMERO",
    "ATS-DE": "ENFERMERO",
    "AYUDANTE TECNICO SANITARIO": "ENFERMERO",
    "DUE": "ENFERMERO",

    # Categorías generales de plaza que incluyen enfermero
    "ENFERMEROS DE INSTITUCIONES PENITENCIARIAS": "ENFERMERO",
    "DIPLOMADOS Y TECNICOS MEDIOS": "ENFERMERO",
    "DIPLOMADOS Y TECNICOS MEDIOS, ESPECIALIDAD ATS/DE DE EMPRESA": "ENFERMERO",

    # Especialistas / áreas, todo sigue siendo ENFERMERO a efectos generales
    "ENFERMERO ESPECIALISTA": "ENFERMERO",
    "ENFERMERA/O ESPECIALISTA": "ENFERMERO",
    "ENFERMERIA FAMILIAR Y COMUNITARIA": "ENFERMERO",
    "ENFERMERIA DE SALUD MENTAL": "ENFERMERO",
    "ENFERMERIA GERIATRICA": "ENFERMERO",
    "ENFERMERO/A ESPECIALISTA EN ENFERMERIA FAMILIAR Y COMUNITARIA": "ENFERMERO",
    "ESPECIALISTAS EN ENFERMERIA FAMILIAR Y COMUNITARIA": "ENFERMERO",
    "ESPECIALISTAS EN PEDIATRIA": "ENFERMERO",
    "ENFERMERO/A ESPECIALISTA OBSTETRICO-GINECOLOGICO (MATRON/A)": "ENFERMERO",
    "ENFERMERA/O ESPECIALIDAD MATRONA": "ENFERMERO",

    # Fórmulas mixtas frecuentes
    "GRADO, DIPLOMADO UNIVERSITARIO DE ENFERMERIA, AYUDANTE TECNICO SANITARIO": "ENFERMERO",
    "GRADO EN ENFERMERIA O DIPLOMADO UNIVERSITARIO EN ENFERMERIA": "ENFERMERO",
    "GRADO EN ENFERMERIA, AYUDANTE TECNICO SANITARIO": "ENFERMERO",
}


# -------------------------------------------------------------------
#  DICCIONARIO: TCAE / AUXILIAR DE ENFERMERÍA
# -------------------------------------------------------------------
# Regla general que tú marcaste:
# TODO LO QUE CONTENGA TECNICO o AUXILIAR + ENFERMERIA pertenece a TCAE/AUXILIAR

PATRONES_TCAE_AUX_ENFERMERIA = {
    # AUXILIARES DE ENFERMERÍA
    "AUXILIAR DE ENFERMERIA": "AUXILIAR_ENFERMERIA",
    "AUXILIARES DE ENFERMERIA": "AUXILIAR_ENFERMERIA",
    "AUXILIAR ENFERMERIA": "AUXILIAR_ENFERMERIA",
    "AUXILIAR DE ENFERMERIA HOSPITALARIA": "AUXILIAR_ENFERMERIA",

    # TCAE
    "TECNICO EN CUIDADOS AUXILIARES DE ENFERMERIA": "TCAE",
    "TECNICOS EN CUIDADOS AUXILIARES DE ENFERMERIA": "TCAE",
    "TECNICO EN CUIDADOS AUXILIARES ENFERMERIA": "TCAE",
    "TECNICO/A EN CUIDADOS AUXILIARES DE ENFERMERIA": "TCAE",
    "TECNICO CUIDADOS AUXILIARES DE ENFERMERIA": "TCAE",
    "TCAE": "TCAE",

    # Otras fórmulas equivalentes de auxiliar sanitaria
    "TECNICO EN AUXILIARES DE ENFERMERIA": "AUXILIAR_ENFERMERIA",
    "TECNICO/A EN AUXILIARES DE ENFERMERIA": "AUXILIAR_ENFERMERIA",
    "TECNICO AUXILIAR DE ENFERMERIA": "AUXILIAR_ENFERMERIA",
    "TECNICO/A AUXILIAR DE ENFERMERIA": "AUXILIAR_ENFERMERIA",

    "TECNICO AUXILIAR DE CLINICA": "AUXILIAR_ENFERMERIA",
    "TECNICO/A AUXILIAR DE CLINICA": "AUXILIAR_ENFERMERIA",
    "TECNICO AUXILIAR DE PSIQUIATRIA": "AUXILIAR_ENFERMERIA",
    "TECNICO/A AUXILIAR DE PSIQUIATRIA": "AUXILIAR_ENFERMERIA",

    # Perfiles muy próximos sociosanitarios
    "TECNICO EN ATENCION A PERSONAS EN SITUACION DE DEPENDENCIA": "AUXILIAR_SOCIOSANITARIO",
    "TECNICO EN ATENCION SOCIOSANITARIA": "AUXILIAR_SOCIOSANITARIO",
    "TECNICO/A EN ATENCION A PERSONAS EN SITUACION DE DEPENDENCIA": "AUXILIAR_SOCIOSANITARIO",
    "TECNICO/A EN ATENCION SOCIOSANITARIA": "AUXILIAR_SOCIOSANITARIO",

    "CERTIFICADO DE PROFESIONALIDAD DE ATENCION SOCIOSANITARIA A PERSONAS DEPENDIENTES EN INSTITUCIONES SOCIALES": "AUXILIAR_SOCIOSANITARIO",
    "CERTIFICADO DE PROFESIONALIDAD DE ATENCION SOCIOSANITARIA A PERSONAS EN EL DOMICILIO": "AUXILIAR_SOCIOSANITARIO",
    "CERTIFICADO DE PROFESIONALIDAD CORRESPONDIENTE A LA OCUPACION DE AUXILIAR DE AYUDA A DOMICILIO": "AUXILIAR_SOCIOSANITARIO",
}
PATRONES_ENFERMEROYTCAES = {
    **PATRONES_ENFERMERO,
    **PATRONES_TCAE_AUX_ENFERMERIA,
}
